# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/workspace/2018.3/zybo_GrabberBoard/system/system.srcs/sources_1/bd/system/ip/system_ila_0_5/system_ila_0_5.xci
# IP: The module: 'system_ila_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/2018.3/zybo_GrabberBoard/system/system.srcs/sources_1/bd/system/ip/system_ila_0_5/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/workspace/2018.3/zybo_GrabberBoard/system/system.srcs/sources_1/bd/system/ip/system_ila_0_5/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/workspace/2018.3/zybo_GrabberBoard/system/system.srcs/sources_1/bd/system/ip/system_ila_0_5/system_ila_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/workspace/2018.3/zybo_GrabberBoard/system/system.srcs/sources_1/bd/system/ip/system_ila_0_5/system_ila_0_5.xci
# IP: The module: 'system_ila_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/workspace/2018.3/zybo_GrabberBoard/system/system.srcs/sources_1/bd/system/ip/system_ila_0_5/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/workspace/2018.3/zybo_GrabberBoard/system/system.srcs/sources_1/bd/system/ip/system_ila_0_5/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Xilinx/workspace/2018.3/zybo_GrabberBoard/system/system.srcs/sources_1/bd/system/ip/system_ila_0_5/system_ila_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
